"""add score_denominator to task_assignments

Revision ID: 3b872a98e31b
Revises: f7788330747a
Create Date: 2026-04-22 19:36:03.149288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b872a98e31b'
down_revision = 'f7788330747a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_denominator', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_column('score_denominator')

    # ### end Alembic commands ###
