"""add description to document table

Revision ID: 5c61ea6bb2c2
Revises: d049935304b3
Create Date: 2025-10-14 03:39:24.014316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c61ea6bb2c2'
down_revision = 'd049935304b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False, server_default=''))
                    
    with op.batch_alter_table('hours', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hours', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
