"""user has picture data

Revision ID: 7d8c03617b73
Revises: 5c61ea6bb2c2
Create Date: 2025-11-03 20:57:14.647014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8c03617b73'
down_revision = '5c61ea6bb2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        op.alter_column('users', 'picture',
               server_default='default.jpeg',
               existing_type=sa.String,
               existing_nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture',
               server_default='default.jpg',
               existing_type=sa.String,
               existing_nullable=False)

    # ### end Alembic commands ###
