"""initial

Revision ID: 914b5159e2da
Revises: 
Create Date: 2025-09-24 21:11:17.707107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914b5159e2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('doctype', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fk_documents_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_documents_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('fk_hours_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_hours_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hours')
    op.drop_table('documents')
    op.drop_table('users')
    # ### end Alembic commands ###
