"""added total hours attribute

Revision ID: c677ca50a5e5
Revises: 594ff0382ba6
Create Date: 2025-12-19 18:17:45.773480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c677ca50a5e5'
down_revision = '594ff0382ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'total_hours',
                sa.Float(),
                nullable=False,
                server_default='0'
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_hours')

    # ### end Alembic commands ###
