"""add recurring tasks and skip review columns

Revision ID: f7788330747a
Revises: 29239bd58779
Create Date: 2026-02-07 16:05:59.645622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7788330747a'
down_revision = '29239bd58779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recurrence_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('skip_review', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('skip_review')
        batch_op.drop_column('recurrence_end_date')
        batch_op.drop_column('recurrence_frequency')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
